import localFont from "next/font/local";
import Header from "@/components/header";
import Footer from "@/components/footer";
import type { Metadata } from "next";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Flex Wear Marketplace",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        ap-style=""
        data-new-gr-c-s-check-loaded="14.1217.0"
        data-gr-ext-installed=""
        >
        <Header />
        {children}
        <Footer />



       
      </body>
    </html >
  );
}
